{"name":"http-restify-error","version":"1.1.0","description":"custom http error for restify package","main":"index.js","scripts":{"test":"echo \"Error: no test specified\" && exit 1"},"repository":"https://github.com/wuriyanto48/http-restify-error","license":"MIT","homepage":"https://github.com/wuriyanto48/http-restify-error#readme","dependencies":{"restify-errors":"^4.3.0"},"gitHead":"897964ffc40b819e05637b919253fa9937f5a5a0","versions":[{"number":"1.0.0","date":"2017-03-07T10:46:37.236Z"},{"number":"1.1.0","date":"2017-03-07T11:05:47.369Z"}],"readme":"- SIMPLE HTTP ERROR CUSTOM FOR RESTIFY\n\nWhen you dealing with callback, sometime you confuse which error you need to handle.\nBecause you don't know where the error comes from.\n\nUSAGE:\n\n-repository.js\n\n```javascript\n\n  'use strict'\n\n  const httpError = require('http-restify-error');\n\n  function find(id, cb){\n    cb({error: httpError.ERROR_TYPE.NOT_FOUND, msg: `user with id ${id} not found`}, null);\n  }\n\n  module.exports = find;\n\n```\n\n-handler.js\n\n```javascript\n\n  'use strict';\n\n  const httpError = require('http-restify-error');\n\n  const find = require('./repository');\n\n  function getExample(req, res, next){\n    let id = 1;\n    find(id, (err, data) => {\n      res.send(httpError.error(err.error, err.msg));\n    });\n  }\n\n  module.exports = {\n    getExample: getExample\n  };\n\n```\n\n-index.js\n\n```javascript\n\n  'use strict';\n\n  const restify = require('restify');\n\n  const handler = require('./handler');\n\n  const server = restify.createServer({\n    versions: \"0.0.1\",\n    name: 'MyApp',\n  });\n\n  server.get('/', (req, res, next) => {\n    res.send(\"Test........\");\n  });\n\n  server.get('/error-test', handler.getExample);\n\n  server.listen(3000);\n\n```\n This package build from https://github.com/restify/errors\n","created":"2017-03-07T10:46:37.236Z","modified":"2017-03-07T11:05:47.369Z","lastPublisher":{"name":"wuriyanto","email":"wuriyanto48@yahoo.co.id"},"owners":[{"name":"wuriyanto","email":"wuriyanto48@yahoo.co.id"}],"other":{"_attachments":{},"_from":".","_id":"http-restify-error","_nodeVersion":"6.9.5","_npmOperationalInternal":{"host":"packages-18-east.internal.npmjs.com","tmp":"tmp/http-restify-error-1.1.0.tgz_1488884745700_0.8688923267181963"},"_npmUser":{"name":"wuriyanto","email":"wuriyanto48@yahoo.co.id"},"_npmVersion":"3.10.10","_rev":"2-5985cd889891c5915576f82ea8acb954","_shasum":"ce4276260f192cd0f895946494a5d20fe5794234","author":{"name":"wuriyanto","email":"wuriyanto48@yahoo.co.id"},"bugs":{"url":"https://github.com/wuriyanto48/http-restify-error/issues"},"directories":{},"dist-tags":{"latest":"1.1.0"},"dist":{"shasum":"ce4276260f192cd0f895946494a5d20fe5794234","tarball":"https://registry.npmjs.org/http-restify-error/-/http-restify-error-1.1.0.tgz"},"maintainers":[{"name":"wuriyanto","email":"wuriyanto48@yahoo.co.id"}],"readmeFilename":"README.md","time":{"modified":"2017-03-07T11:05:47.369Z","created":"2017-03-07T10:46:37.236Z","1.0.0":"2017-03-07T10:46:37.236Z","1.1.0":"2017-03-07T11:05:47.369Z"}}}